import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, users, products }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <main className="container mx-auto p-6">
          {children}
          <div className="flex gap-6 mt-6">
            <div className="flex-none w-1/3 bg-white rounded-lg shadow-lg p-4">
              <h2 className="text-xl font-semibold mb-4">Users</h2>
              {users}
            </div>
            <div className="flex-none w-2/3 bg-white rounded-lg shadow-lg p-4">
              <h2 className="text-xl font-semibold mb-4">Products</h2>
              {products}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
